version: '3.8'
services:
    database:
        container_name: lmsdatabase
        restart: always
        image: postgres:16.1
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        ports:
            - 5432:5432
        volumes:
            - ./Database:/var/lib/postgresql/data
